<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap — PrintFast Digital Marketing</title>
        <style>
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f9fa; color: #1a1a2e; }
          header { background: #1a1a2e; color: #fff; padding: 24px 40px; }
          header h1 { font-size: 22px; font-weight: 700; letter-spacing: -0.3px; }
          header p { font-size: 14px; color: #a0aec0; margin-top: 4px; }
          .container { max-width: 900px; margin: 32px auto; padding: 0 24px; }
          .card { background: #fff; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); overflow: hidden; }
          .card-header { padding: 16px 24px; border-bottom: 1px solid #edf2f7; background: #f7fafc; font-size: 13px; font-weight: 600; color: #718096; text-transform: uppercase; letter-spacing: 0.5px; display: flex; justify-content: space-between; }
          table { width: 100%; border-collapse: collapse; }
          tr:hover td { background: #f7fafc; }
          td { padding: 14px 24px; border-bottom: 1px solid #edf2f7; font-size: 15px; }
          tr:last-child td { border-bottom: none; }
          a { color: #2563eb; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .badge { display: inline-block; background: #ebf4ff; color: #2563eb; border-radius: 4px; padding: 2px 8px; font-size: 12px; font-weight: 600; }
          footer { text-align: center; padding: 24px; font-size: 13px; color: #a0aec0; }
        </style>
      </head>
      <body>
        <header>
          <h1>PrintFast Digital Marketing — XML Sitemap</h1>
          <p>This sitemap lists all pages available for search engine indexing.</p>
        </header>
        <div class="container">
          <div class="card">
            <div class="card-header">
              <span>Page URLs</span>
              <span><xsl:value-of select="count(sm:urlset/sm:url)"/> URLs</span>
            </div>
            <table>
              <xsl:for-each select="sm:urlset/sm:url">
                <tr>
                  <td>
                    <a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a>
                  </td>
                  <td style="text-align:right;width:100px;">
                    <span class="badge">indexed</span>
                  </td>
                </tr>
              </xsl:for-each>
            </table>
          </div>
        </div>
        <footer>Generated by PrintFast Digital Marketing · <a href="https://marketing.print-fast.com">marketing.print-fast.com</a></footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
