#!/usr/bin/env node
/**
 * Renders Nginx config for every app in deploy/apps.json.
 *
 * Two files per app, on purpose:
 *
 *   snippets/pf-<name>.conf        everything volatile — proxy target, ACME
 *                                  challenge root, redirects, body size.
 *                                  Rewritten on every deploy.
 *
 *   sites-available/<domain>.conf  the vhost. Certbot edits this file when it
 *                                  installs TLS, so the deploy only writes it
 *                                  when it does not exist yet. All it does is
 *                                  `include` the snippet, so config changes
 *                                  still land without clobbering certbot.
 *
 * Output goes to deploy/nginx/ (committed, so the server config is reviewable
 * in the repo) and is uploaded verbatim by the deploy workflow.
 *
 * Usage: node scripts/render-nginx.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'deploy', 'apps.json'), 'utf8'));

const OUT = path.join(ROOT, 'deploy', 'nginx');
const SNIPPET_DIR = path.join(OUT, 'snippets');
const VHOST_DIR = path.join(OUT, 'sites-available');

const SNIPPET_PATH = (name) => `/etc/nginx/snippets/pf-${name}.conf`;
const banner = '# Generated by scripts/render-nginx.mjs from deploy/apps.json — do not edit by hand.';

const redirectsFor = (appName) =>
  (manifest.redirects ?? [])
    .filter((r) => r.from === appName)
    .map(
      (r) => `
# ${r.$comment ?? 'Permanent redirect'}
location ~ ${r.location} {
    return 301 ${r.to};
}`
    )
    .join('\n');

const snippet = (app) => `${banner}
# ${app.title} — proxied to the container on 127.0.0.1:${app.hostPort}.

client_max_body_size ${app.maxBodySize ?? '10M'};

# Let's Encrypt HTTP-01 challenge must stay reachable over plain HTTP.
location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
}
${redirectsFor(app.name)}

location / {
    proxy_pass http://127.0.0.1:${app.hostPort};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "";
    proxy_read_timeout 90s;
}
`;

const vhost = (app) => `${banner}
# ${app.title} — https://${app.domain}
#
# Certbot rewrites this file when it installs TLS (adding the :443 server block
# and the HTTP->HTTPS redirect), so deploys never overwrite an existing copy.
# Routing lives in ${SNIPPET_PATH(app.name)} and is refreshed every deploy.

server {
    listen 80;
    listen [::]:80;
    server_name ${app.domain};

    server_tokens off;

    access_log /var/log/nginx/${app.name}.access.log;
    error_log  /var/log/nginx/${app.name}.error.log;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    include ${SNIPPET_PATH(app.name)};
}
`;

const defaultVhost = (app) => `${banner}
# Catch-all for requests that arrive by IP or with an unknown Host header.
# Serves ${app.title} so the VPS is always reachable at http://${manifest.server.fallbackServerName}.

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ${manifest.server.fallbackServerName} _;

    server_tokens off;

    access_log /var/log/nginx/default.access.log;
    error_log  /var/log/nginx/default.error.log;

    include ${SNIPPET_PATH(app.name)};
}
`;

fs.rmSync(SNIPPET_DIR, { recursive: true, force: true });
fs.rmSync(VHOST_DIR, { recursive: true, force: true });
fs.mkdirSync(SNIPPET_DIR, { recursive: true });
fs.mkdirSync(VHOST_DIR, { recursive: true });

const written = [];
for (const app of manifest.apps) {
  fs.writeFileSync(path.join(SNIPPET_DIR, `pf-${app.name}.conf`), snippet(app));
  fs.writeFileSync(path.join(VHOST_DIR, `${app.domain}.conf`), vhost(app));
  written.push(app.domain);
}

const fallbackApp = manifest.apps.find((a) => a.defaultServer) ?? manifest.apps[0];
fs.writeFileSync(path.join(VHOST_DIR, '00-default.conf'), defaultVhost(fallbackApp));

console.log(`render-nginx: ${written.length} vhost(s) + default -> deploy/nginx/`);
for (const domain of written) console.log(`  ${domain}`);
